kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: microservice-production
spec:
  replicas: 1
  template:
    metadata:
      name: microservice
      labels:
        app: x404
        env: production
    spec:
      containers:
      - name: microservice-production
        image: gcr.io/learn-gcp-187312/microservice:v1.1
        resources:
          limits:
            memory: "500Mi"
            cpu: "100m"
        imagePullPolicy: Always
        ports:
        - name: microservice
          containerPort: 3005
